/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sra.kafka.warehouse.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum WarehouseStatus implements org.apache.avro.generic.GenericEnumSymbol<WarehouseStatus> {
  ACTIVE, INACTIVE, CLOSED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WarehouseStatus\",\"namespace\":\"com.sra.kafka.warehouse.avro.model\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"CLOSED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
