/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sra.kafka.inventory.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InventoryRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6039074934587503453L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InventoryRequestAvroModel\",\"namespace\":\"com.sra.kafka.inventory.avro.model\",\"fields\":[{\"name\":\"inventoryId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"warehouseId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InventoryRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<InventoryRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InventoryRequestAvroModel> DECODER =
      new BinaryMessageDecoder<InventoryRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InventoryRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InventoryRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InventoryRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InventoryRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InventoryRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InventoryRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InventoryRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InventoryRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String inventoryId;
  private java.lang.String warehouseId;
  private java.lang.String productId;
  private int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InventoryRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param inventoryId The new value for inventoryId
   * @param warehouseId The new value for warehouseId
   * @param productId The new value for productId
   * @param quantity The new value for quantity
   */
  public InventoryRequestAvroModel(java.lang.String inventoryId, java.lang.String warehouseId, java.lang.String productId, java.lang.Integer quantity) {
    this.inventoryId = inventoryId;
    this.warehouseId = warehouseId;
    this.productId = productId;
    this.quantity = quantity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return inventoryId;
    case 1: return warehouseId;
    case 2: return productId;
    case 3: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: inventoryId = value$ != null ? value$.toString() : null; break;
    case 1: warehouseId = value$ != null ? value$.toString() : null; break;
    case 2: productId = value$ != null ? value$.toString() : null; break;
    case 3: quantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'inventoryId' field.
   * @return The value of the 'inventoryId' field.
   */
  public java.lang.String getInventoryId() {
    return inventoryId;
  }


  /**
   * Sets the value of the 'inventoryId' field.
   * @param value the value to set.
   */
  public void setInventoryId(java.lang.String value) {
    this.inventoryId = value;
  }

  /**
   * Gets the value of the 'warehouseId' field.
   * @return The value of the 'warehouseId' field.
   */
  public java.lang.String getWarehouseId() {
    return warehouseId;
  }


  /**
   * Sets the value of the 'warehouseId' field.
   * @param value the value to set.
   */
  public void setWarehouseId(java.lang.String value) {
    this.warehouseId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Creates a new InventoryRequestAvroModel RecordBuilder.
   * @return A new InventoryRequestAvroModel RecordBuilder
   */
  public static com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder newBuilder() {
    return new com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder();
  }

  /**
   * Creates a new InventoryRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InventoryRequestAvroModel RecordBuilder
   */
  public static com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder newBuilder(com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder();
    } else {
      return new com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new InventoryRequestAvroModel RecordBuilder by copying an existing InventoryRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new InventoryRequestAvroModel RecordBuilder
   */
  public static com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder newBuilder(com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel other) {
    if (other == null) {
      return new com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder();
    } else {
      return new com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for InventoryRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InventoryRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<InventoryRequestAvroModel> {

    private java.lang.String inventoryId;
    private java.lang.String warehouseId;
    private java.lang.String productId;
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.inventoryId)) {
        this.inventoryId = data().deepCopy(fields()[0].schema(), other.inventoryId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[1].schema(), other.warehouseId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing InventoryRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.inventoryId)) {
        this.inventoryId = data().deepCopy(fields()[0].schema(), other.inventoryId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.warehouseId)) {
        this.warehouseId = data().deepCopy(fields()[1].schema(), other.warehouseId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'inventoryId' field.
      * @return The value.
      */
    public java.lang.String getInventoryId() {
      return inventoryId;
    }


    /**
      * Sets the value of the 'inventoryId' field.
      * @param value The value of 'inventoryId'.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder setInventoryId(java.lang.String value) {
      validate(fields()[0], value);
      this.inventoryId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'inventoryId' field has been set.
      * @return True if the 'inventoryId' field has been set, false otherwise.
      */
    public boolean hasInventoryId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'inventoryId' field.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder clearInventoryId() {
      inventoryId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'warehouseId' field.
      * @return The value.
      */
    public java.lang.String getWarehouseId() {
      return warehouseId;
    }


    /**
      * Sets the value of the 'warehouseId' field.
      * @param value The value of 'warehouseId'.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder setWarehouseId(java.lang.String value) {
      validate(fields()[1], value);
      this.warehouseId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'warehouseId' field has been set.
      * @return True if the 'warehouseId' field has been set, false otherwise.
      */
    public boolean hasWarehouseId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'warehouseId' field.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder clearWarehouseId() {
      warehouseId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder setProductId(java.lang.String value) {
      validate(fields()[2], value);
      this.productId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder setQuantity(int value) {
      validate(fields()[3], value);
      this.quantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.sra.kafka.inventory.avro.model.InventoryRequestAvroModel.Builder clearQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InventoryRequestAvroModel build() {
      try {
        InventoryRequestAvroModel record = new InventoryRequestAvroModel();
        record.inventoryId = fieldSetFlags()[0] ? this.inventoryId : (java.lang.String) defaultValue(fields()[0]);
        record.warehouseId = fieldSetFlags()[1] ? this.warehouseId : (java.lang.String) defaultValue(fields()[1]);
        record.productId = fieldSetFlags()[2] ? this.productId : (java.lang.String) defaultValue(fields()[2]);
        record.quantity = fieldSetFlags()[3] ? this.quantity : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InventoryRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<InventoryRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InventoryRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<InventoryRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










