/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sra.kafka.inventory.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum InventoryStatus implements org.apache.avro.generic.GenericEnumSymbol<InventoryStatus> {
  AVAILABLE, OUT_OF_STOCK, RESERVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InventoryStatus\",\"namespace\":\"com.sra.kafka.inventory.avro.model\",\"symbols\":[\"AVAILABLE\",\"OUT_OF_STOCK\",\"RESERVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
